name: 'Tomnomnom Tools Scan'
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  tomnomnom-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y golang
          export GOPATH=$HOME/go
          export PATH=$PATH:$GOPATH/bin
          go install github.com/tomnomnom/assetfinder@latest
          go install github.com/tomnomnom/httprobe@latest
          go install github.com/tomnomnom/gf@latest
        shell: bash

      - name: Run assetfinder
        run: |
          ~/go/bin/assetfinder --subs-only example.com > ${{runner.temp}}/assetfinder.out
        shell: bash

      - name: Run httprobe
        run: |
          cat ${{runner.temp}}/assetfinder.out | ~/go/bin/httprobe > ${{runner.temp}}/httprobe.out
        shell: bash

      - name: Run gf
        run: |
          cat ${{runner.temp}}/httprobe.out | ~/go/bin/gf xss > ${{runner.temp}}/gf-xss.out
        shell: bash

      - name: Display results
        run: |
          echo -e "\n\033[1;34m=== Assetfinder Results ===\033[0m"
          cat ${{runner.temp}}/assetfinder.out
          echo -e "\033[1;34m=== End of Assetfinder Results ===\033[0m\n"
          
          echo -e "\n\033[1;34m=== HTTProbe Results ===\033[0m"
          cat ${{runner.temp}}/httprobe.out
          echo -e "\033[1;34m=== End of HTTProbe Results ===\033[0m\n"
          
          echo -e "\n\033[1;34m=== GF XSS Results ===\033[0m"
          cat ${{runner.temp}}/gf-xss.out
          echo -e "\033[1;34m=== End of GF XSS Results ===\033[0m\n"
        shell: bash

      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: tomnomnom-tools-results
          path: |
            ${{runner.temp}}/assetfinder.out
            ${{runner.temp}}/httprobe.out
            ${{runner.temp}}/gf-xss.out
