name: 'Hackersden Tools Scan'
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  tomnomnom-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y golang
          export GOPATH=$HOME/go
          export PATH=$PATH:$GOPATH/bin
          go install github.com/tomnomnom/assetfinder@latest
          go install github.com/tomnomnom/httprobe@latest
          go install github.com/tomnomnom/gf@latest
          go install github.com/tomnomnom/waybackurls@latest
          go install github.com/tomnomnom/me@latest
          
          # Install crtsh
          mkdir -p ~/go/src/github.com/tomnomnom
          cd ~/go/src/github.com/tomnomnom
          git clone https://github.com/tomnomnom/assetfinder.git
          cd assetfinder
          go build -o ~/go/bin/crtsh crtsh.go
          
          # Install httpx
          go install github.com/projectdiscovery/httpx/cmd/httpx@latest
          
          # Download GF patterns
          mkdir -p ~/.gf
          cd ~/.gf
          git clone https://github.com/1ndianl33t/Gf-Patterns.git
          mv Gf-Patterns/*.json ./
        shell: bash

      - name: Run assetfinder
        run: |
          ~/go/bin/assetfinder --subs-only example.com > ${{runner.temp}}/assetfinder.out
        shell: bash

      - name: Run httprobe
        run: |
          cat ${{runner.temp}}/assetfinder.out | ~/go/bin/httprobe --prefer-https > ${{runner.temp}}/httprobe.out
        shell: bash

      - name: Run gf
        run: |
          find . -type f | ~/go/bin/gf base64 > ${{runner.temp}}/gf-base64.out
        shell: bash

      - name: Run crtsh
        run: |
          ~/go/bin/crtsh example.com > ${{runner.temp}}/crtsh.out
        shell: bash

      - name: Run httpx
        run: |
          cat ${{runner.temp}}/assetfinder.out | ~/go/bin/httpx -ports 80,443,8080,8443 -title -status-code -json > ${{runner.temp}}/httpx.out
        shell: bash

      - name: Run waybackurls
        run: |
          echo example.com | ~/go/bin/waybackurls > ${{runner.temp}}/waybackurls.out
        shell: bash

      - name: Display results
        run: |
          echo -e "\n\033[1;34m=== Assetfinder Results ===\033[0m"
          cat ${{runner.temp}}/assetfinder.out
          echo -e "\033[1;34m=== End of Assetfinder Results ===\033[0m\n"
          
          echo -e "\n\033[1;34m=== HTTProbe Results ===\033[0m"
          cat ${{runner.temp}}/httprobe.out
          echo -e "\033[1;34m=== End of HTTProbe Results ===\033[0m\n"
          
          echo -e "\n\033[1;34m=== GF Base64 Results ===\033[0m"
          cat ${{runner.temp}}/gf-base64.out
          echo -e "\033[1;34m=== End of GF Base64 Results ===\033[0m\n"

          echo -e "\n\033[1;34m=== CRTSH Results ===\033[0m"
          cat ${{runner.temp}}/crtsh.out
          echo -e "\033[1;34m=== End of CRTSH Results ===\033[0m\n"
          
          echo -e "\n\033[1;34m=== HTTPX Results ===\033[0m"
          cat ${{runner.temp}}/httpx.out
          echo -e "\033[1;34m=== End of HTTPX Results ===\033[0m\n"
          
          echo -e "\n\033[1;34m=== WaybackURLs Results ===\033[0m"
          cat ${{runner.temp}}/waybackurls.out
          echo -e "\033[1;34m=== End of WaybackURLs Results ===\033[0m\n"
        shell: bash

      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: tomnomnom-tools-results
          path: |
            ${{runner.temp}}/assetfinder.out
            ${{runner.temp}}/httprobe.out
            ${{runner.temp}}/gf-base64.out
            ${{runner.temp}}/crtsh.out
            ${{runner.temp}}/httpx.out
            ${{runner.temp}}/waybackurls.out
