name: 'Tomnomnom Tools Scan'
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  tomnomnom-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'  # Ensure compatibility with the tools

      - name: Install tools
        run: |
          export GOPATH=$HOME/go
          export PATH=$PATH:$GOPATH/bin
          go install github.com/tomnomnom/assetfinder@latest
          go install github.com/tomnomnom/httprobe@latest
          go install github.com/tomnomnom/waybackurls@latest
          go install github.com/projectdiscovery/httpx/cmd/httpx@latest
          
          # Install additional tools
          sudo apt-get update
          sudo apt-get install -y anew fff
          go install github.com/tomnomnom/gf@latest
        shell: bash

      - name: Run assetfinder
        run: |
          ~/go/bin/assetfinder --subs-only example.com > ${{runner.temp}}/assetfinder.out
        shell: bash

      - name: Run httprobe
        run: |
          cat ${{runner.temp}}/assetfinder.out | ~/go/bin/httprobe -p 80,443 > ${{runner.temp}}/httprobe.out
        shell: bash

      - name: Run waybackurls
        run: |
          echo example.com | ~/go/bin/waybackurls > ${{runner.temp}}/waybackurls.out
        shell: bash

      - name: Run httpx
        run: |
          cat ${{runner.temp}}/assetfinder.out | ~/go/bin/httpx -ports 80,443,8080,8443 -title -status-code -json > ${{runner.temp}}/httpx.out
        shell: bash

      - name: Additional Commands
        run: |
          cat ${{runner.temp}}/httprobe.out | anew ${{runner.temp}}/domains
          cat ${{runner.temp}}/domains | ~/go/bin/httprobe -c 50 | anew ${{runner.temp}}/hosth
          cat ${{runner.temp}}/hosth | fff -d 1 -S -o ${{runner.temp}}/roots
          ~/go/bin/gf meg-headers < ${{runner.temp}}/roots
          ~/go/bin/gf servers < ${{runner.temp}}/roots | anew ${{runner.temp}}/gf-servers
        shell: bash

      - name: Display results
        run: |
          echo -e "\n\033[1;34m=== Assetfinder Results ===\033[0m"
          cat ${{runner.temp}}/assetfinder.out
          echo -e "\033[1;34m=== End of Assetfinder Results ===\033[0m\n"
          
          echo -e "\n\033[1;34m=== HTTProbe Results ===\033[0m"
          cat ${{runner.temp}}/httprobe.out
          echo -e "\033[1;34m=== End of HTTProbe Results ===\033[0m\n"
          
          echo -e "\n\033[1;34m=== WaybackURLs Results ===\033[0m"
          cat ${{runner.temp}}/waybackurls.out
          echo -e "\033[1;34m=== End of WaybackURLs Results ===\033[0m\n"
          
          echo -e "\n\033[1;34m=== HTTPX Results ===\033[0m"
          cat ${{runner.temp}}/httpx.out
          echo -e "\033[1;34m=== End of HTTPX Results ===\033[0m\n"
          
          echo -e "\n\033[1;34m=== Additional Results ===\033[0m"
          cat ${{runner.temp}}/domains
          cat ${{runner.temp}}/hosth
          cat ${{runner.temp}}/roots
          cat ${{runner.temp}}/gf-servers
          echo -e "\033[1;34m=== End of Additional Results ===\033[0m\n"
        shell: bash

      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: tomnomnom-tools-results
          path: |
            ${{runner.temp}}/assetfinder.out
            ${{runner.temp}}/httprobe.out
            ${{runner.temp}}/waybackurls.out
            ${{runner.temp}}/httpx.out
            ${{runner.temp}}/domains
            ${{runner.temp}}/hosth
            ${{runner.temp}}/roots
            ${{runner.temp}}/gf-servers
